from pathlib import Path
from typing import Dict, Any

# @feature [MARKDOWN_FOR-01] Markdown formatter
class MarkdownFormatter:
    """Formats feature graph into a rich Markdown table and Mermaid dependency diagram."""

    @staticmethod
    # @feature [MARKDOWN_FOR-02] Format
    def format(graph_dict: Dict[str, Any], root_dir: Path) -> str:
        rows = []
        mermaid_edges = []

        for feat_id, data in sorted(graph_dict.items()):
            name = data.get("name", feat_id)
            desc = data.get("description", "")
            deps = data.get("depends_on", [])
            called_by = data.get("called_by", [])
            locations = data.get("locations", [])

            # Mermaid edge construction
            for dep in deps:
                mermaid_edges.append(f"    {feat_id}[\"{feat_id}: {name}\"] --> {dep}")

            dep_str = " ".join([f"`[{d}]`" for d in deps]) if deps else "—"
            call_str = " ".join([f"`[{c}]`" for c in called_by]) if called_by else "—"

            loc_links = []
            for loc in locations[:4]:  # cap at 4 per feature to keep table scannable
                file_rel = loc.get("file", "")
                s_line = loc.get("start_line", 1)
                e_line = loc.get("end_line", s_line + 10)
                file_name = Path(file_rel).name
                loc_links.append(f"[`{file_name}:{s_line}-{e_line}`](file://{root_dir / file_rel}#L{s_line}-L{e_line})")

            loc_str = "<br>".join(loc_links) if loc_links else "—"
            rows.append(f"| **`{feat_id}`** | **{name}** | {desc} | {dep_str} | {call_str} | {loc_str} |")

        mermaid_block = ""
        if mermaid_edges:
            mermaid_block = "```mermaid\ngraph TD\n" + "\n".join(mermaid_edges[:40]) + "\n```\n\n---\n"  # cap at 40 edges for readable Mermaid output

        return f"""# System Feature Dependency Graph

> **CRITICAL CONTRACT FOR AI ASSISTANTS & DEVELOPERS:**
> This graph is generated by `featuregraph`. 
> Always inspect dependencies before modifying or deleting code.

---

## 1. Visual Dependency Graph

{mermaid_block}## 2. Feature Map & Exact Line Reference Matrix

| Feature ID | Feature Name | Description | Depends On | Called By | Exact Line References |
| :--- | :--- | :--- | :--- | :--- | :--- |
""" + "\n".join(rows) + """

---

## 3. Token-Efficient Reading Protocol

When working on any feature:
1. Lookup `FEATURE_INDEX.json` to get the exact line slice (`#Lstart-Lend`).
2. Read **only** those lines with your editor tool.
3. Check `[Depends On]` features before committing changes.
"""

    @staticmethod
    # @feature [MARKDOWN_FOR-03] Write to file
    def write_to_file(graph_dict: Dict[str, Any], output_path: Path, root_dir: Path):
        content = MarkdownFormatter.format(graph_dict, root_dir)
        output_path.write_text(content, encoding="utf-8")
